import { describe, expect, it } from 'vitest';
import type { LedPreset } from '@bt-led/led-types';
import { generateArduinoCode } from './CodeGenerator';

const preset = (overrides: Partial<LedPreset['config']>): LedPreset => ({
  id: 'live',
  name: 'Test Preset',
  createdAt: '2026-05-12T00:00:00Z',
  version: 1,
  config: {
    pattern: 'solid',
    color: { r: 12, g: 34, b: 56 },
    speed: 50,
    brightness: 200,
    powerMode: 1,
    ...overrides,
  },
});

describe('generateArduinoCode', () => {
  it('emits a self-contained customPattern() wrapper', () => {
    const code = generateArduinoCode(preset({}));
    expect(code).toMatch(/void customPattern\(\)/);
    expect(code).toMatch(/showLeds\(\);/);
    expect(code).toMatch(/ledBufferChanged = true;/);
  });

  it('solid pattern bakes the RGB values inline', () => {
    expect(generateArduinoCode(preset({ pattern: 'solid' }))).toMatchInlineSnapshot(`
      "// Generated by LED Simulator
      // Preset: Test Preset
      // Pattern: solid · color rgb(12, 34, 56)
      // Speed: 50 · Brightness: 200
      void customPattern() {
        // Solid colour from preset (overrides currentSettings.color)
        fill_solid_buf(12, 34, 56);
        ledBufferChanged = true;
        showLeds();
      }
      "
    `);
  });

  it('pulse pattern emits the firmware sin8_approx pipeline with baked speed', () => {
    expect(
      generateArduinoCode(preset({ pattern: 'pulse', speed: 75 })),
    ).toMatchInlineSnapshot(`
      "// Generated by LED Simulator
      // Preset: Test Preset
      // Pattern: pulse · color rgb(12, 34, 56)
      // Speed: 75 · Brightness: 200
      void customPattern() {
        // Pulse with sine-wave brightness — speed maps to pulse period.
        uint8_t r = 12;
        uint8_t g = 34;
        uint8_t b = 56;

        uint32_t now = millis();
        uint16_t pulsePeriod = map(75, 0, 100, 4000, 500);
        uint8_t pulsePhase = (uint8_t)((now % pulsePeriod) * 255 / pulsePeriod);
        uint8_t pulseBrightness = sin8_approx(pulsePhase);

        for (int i = 0; i < LED_COUNT; i++) {
          ledBuf[i].r = (uint8_t)((uint16_t)r * pulseBrightness / 255);
          ledBuf[i].g = (uint8_t)((uint16_t)g * pulseBrightness / 255);
          ledBuf[i].b = (uint8_t)((uint16_t)b * pulseBrightness / 255);
        }
        ledBufferChanged = true;
        showLeds();
      }
      "
    `);
  });

  it('strobe pattern uses the map(speed, …) cadence from the firmware', () => {
    const out = generateArduinoCode(preset({ pattern: 'strobe', speed: 0 }));
    expect(out).toMatch(/strobePeriod = map\(0, 0, 100, 1000, 50\);/);
    expect(out).toMatch(/fill_solid_buf\(12, 34, 56\);/);
    expect(out).toMatch(/clearBuf\(\);/);
  });

  it('wave pattern emits the inline HSV wave loop (no fallback call)', () => {
    const out = generateArduinoCode(preset({ pattern: 'wave', speed: 80 }));
    expect(out).toMatch(/speedShift = map\(80, 0, 100, 4, 1\);/);
    expect(out).toMatch(/hsv2rgb\(wavePhase, 255, v\);/);
    // Self-contained — no call back to the firmware's wave() wrapper.
    expect(out).not.toMatch(/^\s*wave\(\);/m);
  });

  it('rainbow / chase / twinkle / breath / fade / off all emit inline bodies', () => {
    for (const pattern of ['rainbow', 'chase', 'twinkle', 'breath', 'fade', 'off'] as const) {
      const out = generateArduinoCode(preset({ pattern }));
      // No bare firmware function call — body is inline.
      expect(out, `pattern=${pattern}`).not.toMatch(new RegExp(`^\\s*${pattern}\\(\\);`, 'm'));
      expect(out, `pattern=${pattern}`).toMatch(/customPattern/);
    }
  });

  it('fire / meteor / colorwipe / plasma are flagged as simulator-only', () => {
    for (const pattern of ['fire', 'meteor', 'colorwipe', 'plasma'] as const) {
      const out = generateArduinoCode(preset({ pattern }));
      expect(out, `pattern=${pattern}`).toMatch(/simulator-only/);
      // Still a valid C++ body — must compile, hence a clearBuf() call.
      expect(out, `pattern=${pattern}`).toMatch(/clearBuf\(\);/);
    }
  });
});
