import type { LedPreset, PatternId } from '@bt-led/led-types';

// Generates a self-contained C++ function body that drops into bt-led-controller.ino
// alongside the existing pattern functions. Uses ONLY helpers already present in
// the firmware: sin8_approx, beat8_like, fill_solid_buf, fadeToBlackBy_buf, ledBuf,
// currentSettings, LED_COUNT, gamma8, hsv2rgb, blend_rgb.

const indent = (s: string, n = 2): string =>
  s
    .split('\n')
    .map((l) => (l.length ? ' '.repeat(n) + l : l))
    .join('\n');

interface BodyBuilder {
  (preset: LedPreset): string;
}

const BODY: Partial<Record<PatternId, BodyBuilder>> = {
  off: () => 'clearBuf();',

  solid: ({ config }) =>
    [
      `// Solid colour from preset (overrides currentSettings.color)`,
      `fill_solid_buf(${config.color.r}, ${config.color.g}, ${config.color.b});`,
    ].join('\n'),

  pulse: ({ config }) =>
    [
      `// Pulse with sine-wave brightness — speed maps to pulse period.`,
      `uint8_t r = ${config.color.r};`,
      `uint8_t g = ${config.color.g};`,
      `uint8_t b = ${config.color.b};`,
      ``,
      `uint32_t now = millis();`,
      `uint16_t pulsePeriod = map(${config.speed}, 0, 100, 4000, 500);`,
      `uint8_t pulsePhase = (uint8_t)((now % pulsePeriod) * 255 / pulsePeriod);`,
      `uint8_t pulseBrightness = sin8_approx(pulsePhase);`,
      ``,
      `for (int i = 0; i < LED_COUNT; i++) {`,
      `  ledBuf[i].r = (uint8_t)((uint16_t)r * pulseBrightness / 255);`,
      `  ledBuf[i].g = (uint8_t)((uint16_t)g * pulseBrightness / 255);`,
      `  ledBuf[i].b = (uint8_t)((uint16_t)b * pulseBrightness / 255);`,
      `}`,
    ].join('\n'),

  strobe: ({ config }) =>
    [
      `// Strobe — speed maps to flash period; baked color from preset.`,
      `uint32_t now = millis();`,
      `uint16_t strobePeriod = map(${config.speed}, 0, 100, 1000, 50);`,
      `bool strobeState = ((now / strobePeriod) % 2) == 0;`,
      ``,
      `if (strobeState) {`,
      `  fill_solid_buf(${config.color.r}, ${config.color.g}, ${config.color.b});`,
      `} else {`,
      `  clearBuf();`,
      `}`,
    ].join('\n'),
};

const FALLBACK_NOTE: Partial<Record<PatternId, string>> = {
  rainbow: 'rainbow();',
  fade: 'fill_solid_buf(255, 255, 255);',
  chase: 'chase();',
  twinkle: 'twinkle();',
  wave: 'wave();',
  breath: 'breath();',
  fire: '// fire is simulator-only — port the heat array first.',
};

export function generateArduinoCode(preset: LedPreset): string {
  const { config, name } = preset;
  const builder = BODY[config.pattern];
  const inner = builder
    ? builder(preset)
    : `// Reference existing firmware helper:\n${FALLBACK_NOTE[config.pattern] ?? '// not yet generated'}`;

  const header = [
    `// Generated by LED Simulator`,
    `// Preset: ${name}`,
    `// Pattern: ${config.pattern} · color rgb(${config.color.r}, ${config.color.g}, ${config.color.b})`,
    `// Speed: ${config.speed} · Brightness: ${config.brightness}`,
  ].join('\n');

  return `${header}\nvoid customPattern() {\n${indent(inner)}\n  ledBufferChanged = true;\n  showLeds();\n}\n`;
}
